### ISSUE TITLE
Precision might not be sufficient for certain tokens with high value of lowest unit of token

### ISSUE THREAD

**Issue by prateekreddy** [marlinprotocol/Contracts#64]
[Precision of rate](https://github.com/marlinprotocol/Contracts/blob/895d4b6eaa534c6ecd72286f08f419607df240e5/contracts/enclaves/MarketV1.sol#L203) which is in tokens in lowest units per seconds might not be sufficient to represent low price values for tokens like USDC.

**Comment by roshanrags** [comment]
Because of only 6 decimals?
